services:
  server:
    image: studenthub-server:latest
    build:
      context: ../server
      dockerfile: ../server/deploy/Dockerfile
    container_name: studenthub_server
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env

  client:
    image: studenthub-client:latest
    build:
      context: ../client
      dockerfile: ../client/deploy/Dockerfile
      args:
        VITE_BACKEND_URL: ${VITE_BACKEND_URL}
    container_name: studenthub_client
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - server
